import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Lato } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";

import "./globals.css";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "DemPro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
          <Toaster
            position="top-center"
            toastOptions={{
              classNames: {
                loading: "!bg-dpro-secondary !text-sm !font-bold",
                success: "!bg-dpro-secondary !text-sm !font-bold",
                error: "!bg-dpro-secondary !text-sm !font-bold",
              },
            }}
          />
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
