export const tags = [
  { value: "Poster", label: "Poster" },
  { value: "Infographic", label: "Infographic" },
  { value: "Photojournalism", label: "Photojournalism" },
  { value: "Documentary", label: "Documentary" },
  { value: "Social Media Campaign", label: "Social Media Campaign" },
  { value: "Short Video / Reel", label: "Short Video / Reel" },
  { value: "Interview Series", label: "Interview Series" },
  { value: "Podcast / Audio Story", label: "Podcast / Audio Story" },
  { value: "Blog / Written Story", label: "Blog / Written Story" },
  { value: "Workshop Toolkit", label: "Workshop Toolkit" },
  { value: "Educational Material", label: "Educational Material" },
  { value: "Awareness Campaign", label: "Awareness Campaign" },
  { value: "Survey / Poll Report", label: "Survey / Poll Report" },
  { value: "Event Summary / Report", label: "Event Summary / Report" },
  {
    value: "Petition / Civic Action Tools",
    label: "Petition / Civic Action Tools",
  },
];

export const topics = [
  { value: "Youth Participation", label: "Youth Participation" },
  { value: "Minority Inclusion", label: "Minority Inclusion" },
  { value: "Human Rights", label: "Human Rights" },
  { value: "Political Participation", label: "Political Participation" },
  { value: "Elections & Voting", label: "Elections & Voting" },
  { value: "Community Building", label: "Community Building" },
  { value: "Media & Disinformation", label: "Media & Disinformation" },
  {
    value: "Environmental Sustainability",
    label: "Environmental Sustainability",
  },
  { value: "Gender Equality", label: "Gender Equality" },
  { value: "Civic Education", label: "Civic Education" },
  { value: "Social Innovation", label: "Social Innovation" },
  { value: "Digital Activism", label: "Digital Activism" },
  { value: "Public Policy Advocacy", label: "Public Policy Advocacy" },
  { value: "Local Governance", label: "Local Governance" },
  { value: "Volunteerism", label: "Volunteerism" },
  { value: "Cultural Inclusion", label: "Cultural Inclusion" },
  { value: "Access to Justice", label: "Access to Justice" },
  { value: "Youth Leadership", label: "Youth Leadership" },
];
